name: CI
on:
  pull_request:
jobs:
  lint:
    name: Run PSSA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: martincostello/lint-actions-powershell@v1
        with:
          settings-path: .vscode/PSScriptAnalyzerSettings.psd1
          treat-warnings-as-errors: true
          repo-path: PowerFGT