name: Release

on:
  release:
    types: [published]

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Publish
        shell: pwsh
        run: |
          Publish-Module -Path ./PowerFGT -NuGetApiKey ${{ secrets.PSGALLERY_API_KEY }}

  tweet:
    needs: publish-to-gallery
    runs-on: ubuntu-latest
    steps:
      - uses: Eomm/why-don-t-you-tweet@v2
        # We don't want to tweet if the repository is not a public one
        if: ${{ !github.event.repository.private }}
        with:
          # GitHub event payload
          # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#release
          tweet-message: "New ${{ github.event.repository.name }} release ${{ github.event.release.tag_name }}! More information => ${{ github.event.release.html_url }} #PowerFGT @Fortinet"
          TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

  bsky-post:
    needs: publish-to-gallery
    runs-on: ubuntu-latest
    steps:
      - uses: zentered/bluesky-post-action@v0.1.0
        with:
          post: "New ${{ github.event.repository.name }} release ${{ github.event.release.tag_name }}! More information => ${{ github.event.release.html_url }} #PowerFGT @Fortinet"
        env:
          BSKY_IDENTIFIER: ${{ secrets.BSKY_IDENTIFIER }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
