name: tweet

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install BlueBirdPS
      shell: pwsh
      run: |
        Install-Module BlueBirdPS
        Import-Module BlueBirdPS
    - name: Configure BlueBirdPS
      shell: pwsh
      run: |
        Set-TwitterAuthentification -apikey (ConvertTo-SecureString $ENV:TWITTER_CONSUMER_API_KEY -AsPlainText -Force) \
                                    -apisecret (ConvertTo-SecureString $ENV:TWITTER_CONSUMER_API_SECRET -AsPlainText -Force) \
                                    -accesstoken (ConvertTo-SecureString $ENV:TWITTER_ACCESS_TOKEN -AsPlainText -Force) \
                                    -accesssecret (ConvertTo-SecureString $ENV:TWITTER_ACCESS_TOKEN_SECRET -AsPlainText -Force)
      env:
        # Get your tokens from https://developer.twitter.com/apps
        TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
        TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

    - name: Publish Tweet
      shell: pwsh
      run: |
        Publish-Tweet -TweetText "A (bot) Tweet using #BlueBirdPS and Github Actions :)"