name: tweet

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: Eomm/why-don-t-you-tweet@v1
      if: ${{ !github.event.repository.private }}
      with:
        # GitHub event payload
        # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#release
        tweet-message: "Test Tweet API Git Hub Actions"
      env:
        # Get your tokens from https://developer.twitter.com/apps
        TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
        TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        RUNNER_DEBUG: 1